### ISSUE TITLE
:) ???

### ISSUE THREAD

**Issue by rokarc** [juancarlospaco/vacap#4]
Se puede programar un periodicidad para crear los bkp automaticamente?
Los usuarios suelen olvidarse que tienen que hacerlo.
Quizas podría, utilizar una cuenta de mail que coodine con el calendario de su cuenta de mail y le recuerde hacer el bkp.

Tendria que configurar su cuenta de correo.

Se podría hacer que el bkp lo haga al inicio.

Tambièn podriamos hacer que ante un log de falta de espacio nos envia a nosotros un mail.
Para coodinar actualización.

Al año de uso, tendría salir un cartel que necesita actualización.

**Comment by ghost** [comment]
``` python
MAKE_BACKUP_ON_STARTUP = True
MAKE_BACKUP_WHEN_RUNNING_ON_BATTERY = True
MAKE_BACKUP_AT_THIS_HOURS = (12, 18)
```
- MAKE_BACKUP_ON_STARTUP si es `True` hace 1 Backup al inicio, si es `False` no hace nada.
- MAKE_BACKUP_WHEN_RUNNING_ON_BATTERY si es `True` hace Backups cuando la Notebook/NetBook esta corriendo en Bateria.
- MAKE_BACKUP_WHEN_RUNNING_ON_BATTERY si es `False` NO hace backups cuando la Notebook/NetBook esta corriendo en Bateria.
- MAKE_BACKUP_AT_THIS_HOURS hace 1 Backup a esa hora del dia, si la PC esta encendida.
- MAKE_BACKUP_AT_THIS_HOURS si esta Vacio `( , )` Deshabilita el Backup por Horas.

**Nuevo:**
- Click Izquierdo y Click Derecho funcionan por igual para mostrar el Menu mas Facilmente.

**Probar:**
- La funcionalidad que detecta si la Notebook esta corriendo en baterias deberia ser probada, la idea es que si esta andando a baterias no se ponga a hacer backup por que va a consumir la carga de la bateria @rokarc 

:hamster:

**Comment by rokarc** [comment]
La vacap camina solita, esta siendo cada dia mas inteligente :smile: 
:cow:  :cow:  :cow:

**Comment by ghost** [comment]
**Nuevo:**

``` python
MAKE_BACKUP_ONLY_ON_WEEKENDS = True
```
- Si `MAKE_BACKUP_ONLY_ON_WEEKENDS` es `True` hace Backups **Sabado y Domingo** unicamente.
- Si `MAKE_BACKUP_ONLY_ON_WEEKENDS` es `False` hace Backups **Lunes, Martes, Miercoles, Jueves, Viernes** unicamente.

:cow2:
